spring:
                           datasource:
                             username: "root"
                             password: "08099"
                             url: "jdbc:mysql://localhost:3306/spring_library"
                           jpa:
                               database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
                               properties:
                                   hibernate:
                                       current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
                                       dialect: org.hibernate.dialect.MySQL5Dialect
                                       format_sql: true
                               show-sql: true


#                           data:
#                                mongodb:
#                                  host: localhost
#                                  port: 27017
#                                  database: GenreDb
